spring.application.name=foodCatalogue

server.port = 9095

spring.profiles.active = dev

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.datasource.url = ${DB_URL}/foodCatalogue
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
